# Generated by Django 3.2.8 on 2021-12-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delfipq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delfipq_l0_telemetry',
            name='version',
            field=models.TextField(null=True),
        ),
    ]
