# Generated by Django 3.2.8 on 2021-12-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
