# Generated by Django 4.2.10 on 2024-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
