# Generated by Django 3.2.8 on 2021-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
