# Generated by Django 3.2.8 on 2021-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='last_changed',
            field=models.DateField(null=True),
        ),
    ]
