# Generated by Django 3.2.8 on 2022-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='maidenhead_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
