# Generated by Django 3.2.8 on 2022-02-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_apikey'),
        ('members', '0002_auto_20220203_2257'),
    ]

    operations = [
    ]
