# Generated by Django 3.2.8 on 2022-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_merge_0002_apikey_0002_auto_20220203_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
