# Generated by Django 3.2.8 on 2021-11-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20211110_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='username',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='username',
            field=models.CharField(max_length=70),
        ),
    ]
