# Generated by Django 3.2.8 on 2021-11-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='last_changed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
