version: '3.7'

services:
    app:
        volumes:
            - static_data:/vol/web
            - app_logs:/app/logs
        environment:
            # TODO: change the key
            # could also add database config here and remove it from settings.py
            - DEBUG=0
            - SECRET_KEY=${SECRET_KEY:-qwerty}
            - ALLOWED_HOSTS=${MY_HOST:-localhost,127.0.0.1}
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - FROM_EMAIL=${FROM_EMAIL:-webmaster@localhost}
        restart: always

    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol:ro
            - certificates:/certs:ro
        ports:
            - "80:8080"
            - "443:8443"
        environment:
            - MY_HOST=${MY_HOST:-localhost}
        depends_on:
            - app
            - pgadmin
            - grafana
        restart: always

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4:6.5
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
        depends_on:
            - "db"
        volumes:
            - pgadmin_persistent:/var/lib/pgadmin
volumes:
    app_logs:
    static_data:
    certificates:
    pgadmin_persistent:
