# runs local docker container on localhost, port 8000
# this is not used for deployment
version: '3.7'

services:
  db:
    image: postgres:16.0
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-delfitlm}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    restart: always

    logging:
      driver: "json-file"
      options:
        max-file: "5"   # file count
        max-size: "10m" # file size

  app:
    build:
        context: .
    volumes:
      - ./src/home/temp/:/app/home/temp/
    environment:
        - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
        - POSTGRES_DB=${POSTGRES_DB:-delfitlm}
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
        - POSTGRES_HOST=${POSTGRES_HOST:-db}
        - POSTGRES_PORT=${POSTGRES_PORT:-5432}
        - INFLUXDB_V2_ORG=${INFLUXDB_V2_ORG:-DelfiSpace}
        - INFLUXDB_V2_TOKEN=${INFLUXDB_V2_TOKEN:-adminpwd}
    restart: always
    depends_on:
      - "db"
      - "grafana"
      - "influxdb"
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # file count
        max-size: "10m" # file size


  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
    volumes:
      - influxdb_storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD:-adminpwd}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_V2_ORG:-DelfiSpace}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET:-default}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_V2_TOKEN:-adminpwd}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # file count
        max-size: "10m" # file size

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN:-localhost}
      - GF_INFLUXDB_V2_TOKEN=${INFLUXDB_V2_TOKEN:-adminpwd}
      - INFLUXDB_V2_ORG=${INFLUXDB_V2_ORG:-DelfiSpace}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # file count
        max-size: "10m" # file size


volumes:
    db_data:
    influxdb_storage:
    grafana_storage:
