version: '3.3'

services:
    app:
        volumes:
            - static_data:/vol/web
        environment:
            # TODO: change the key
            # could also add database config here and remove it from settings.py
            - DEBUG=0
            - SECRET_KEY=qwerty
            - ALLOWED_HOSTS=localhost,127.0.0.1
    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "80:8080"
        depends_on:
            - app

volumes:
    static_data:
