# runs local docker container on localhost, port 8000
# this is not used for deployment
version: '3.7'

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./src:/DelfiTLM
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DEBUG=1
