{
 "title": "EPS",
 "time": { "from": "2022-01-13T00:00:00.000Z", "to": "2024-01-08T23:59:59.999Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Solar Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solar Panels Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpCurrent\" or r[\"_field\"] == \"PanelYmCurrent\" or r[\"_field\"] == \"PanelXpCurrent\" or r[\"_field\"] == \"PanelXmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpVoltage\" or r[\"_field\"] == \"PanelYmVoltage\" or r[\"_field\"] == \"PanelXpVoltage\" or r[\"_field\"] == \"PanelXmVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns:[\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpTemperature\" or r[\"_field\"] == \"PanelXmTemperature\" or r[\"_field\"] == \"PanelXpTemperature\" or r[\"_field\"] == \"PanelYmTemperature\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Cells Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CellXpVoltage\" or r[\"_field\"] == \"CellXmVoltage\" or r[\"_field\"] == \"CellYpVoltage\" or r[\"_field\"] == \"CellYmVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Cells Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"CellXpCurrent\" or r[\"_field\"] == \"CellXmCurrent\" or r[\"_field\"] == \"CellYpCurrent\" or r[\"_field\"] == \"CellYmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MPPT Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MpptXpVoltage\" or r[\"_field\"] == \"MpptXmVoltage\" or r[\"_field\"] == \"MpptYpVoltage\" or r[\"_field\"] == \"MpptYmVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MPPT Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MpptXpCurrent\" or r[\"_field\"] == \"MpptXmCurrent\" or r[\"_field\"] == \"MpptYpCurrent\" or r[\"_field\"] == \"MpptYmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Battery Current ",
   "type": "timeseries",
   "description": "Battery Current",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryINACurrent\" )\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Voltage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryINAVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Temperture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryGGTemperature\" or r[\"_field\"] == \"BatteryTMP20Temperature\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryGGCapacity\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Main Board", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "EPS Currents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"UnregulatedINACurrent\" or r[\"_field\"] == \"InternalINACurrent\" or r[\"_field\"] == \"Bus1Current\" or r[\"_field\"] == \"Bus2Current\" or r[\"_field\"] == \"Bus3Current\" or r[\"_field\"] == \"Bus4Current\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EPS Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Bus1Voltage\" or r[\"_field\"] == \"Bus2Voltage\" or r[\"_field\"] == \"Bus3Voltage\" or r[\"_field\"] == \"Bus4Voltage\" or r[\"_field\"] == \"InternalINAVoltage\" or r[\"_field\"] == \"UnregulatedINAVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EPS Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MCUTemp\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EPS Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Uptime\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Solar Panels Current Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpCurrent\" or r[\"_field\"] == \"PanelYmCurrent\" or r[\"_field\"] == \"PanelXpCurrent\" or r[\"_field\"] == \"PanelXmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] != \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Current Anomaly",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BatteryINACurrent\")\n  |> filter(fn: (r) => r[\"status\"] != \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EPS Voltage Anomalies ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Bus1Voltage\" or r[\"_field\"] == \"Bus2Voltage\" or r[\"_field\"] == \"Bus3Voltage\" or r[\"_field\"] == \"Bus4Voltage\" or r[\"_field\"] == \"BatteryGGVoltage\" or r[\"_field\"] == \"UnregulatedINAVoltage\" or r[\"_field\"] == \"InternalINAVoltage\")\n  |> filter(fn: (r) => r[\"status\"] != \"Valid\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}