# Generated by Django 3.2.8 on 2021-12-16 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_time', models.TimeField(default=datetime.time)),
                ('send_time', models.TimeField(default=datetime.time)),
                ('receive_time', models.TimeField(default=datetime.time)),
                ('frame', models.TextField(default=None, null=True)),
                ('frame_binary', models.BinaryField(default=None, null=True)),
                ('version', models.TextField(null=True)),
                ('processed', models.BooleanField(default=False)),
                ('frequency', models.FloatField(default=None, null=True)),
                ('qos', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_amateur_username', models.CharField(max_length=70)),
                ('created_at', models.TimeField()),
                ('transmitted_at', models.TimeField(null=True)),
                ('data', models.BinaryField()),
                ('frequency', models.FloatField()),
                ('sat', models.CharField(max_length=70)),
            ],
        ),
    ]
