# Generated by Django 3.2.8 on 2021-12-19 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewilgs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downlink',
            name='frame_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='receive_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='frame_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
