# Generated by Django 3.2.8 on 2021-12-16 02:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ewilgs', '0002_uplink_uuid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downlink',
            name='data',
        ),
        migrations.RemoveField(
            model_name='downlink',
            name='received_at',
        ),
        migrations.AddField(
            model_name='downlink',
            name='frame',
            field=models.BinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='downlink',
            name='frame_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='downlink',
            name='qos',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='downlink',
            name='radio_amateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='downlink',
            name='receive_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='downlink',
            name='send_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='downlink',
            name='version',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='frequency',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
