# Generated by Django 3.2.8 on 2022-02-06 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ewilgs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=70, unique=True)),
                ('norad_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='downlink',
            name='frame_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='receive_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='frame_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(null=True)),
                ('tle', models.TextField()),
                ('sat', models.ForeignKey(db_column='sat', on_delete=django.db.models.deletion.DO_NOTHING, to='ewilgs.satellite', to_field='sat')),
            ],
        ),
        migrations.AddField(
            model_name='downlink',
            name='sat',
            field=models.ForeignKey(db_column='sat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ewilgs.satellite', to_field='sat'),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='sat',
            field=models.ForeignKey(db_column='sat', on_delete=django.db.models.deletion.DO_NOTHING, to='ewilgs.satellite', to_field='sat'),
        ),
    ]
