# Generated by Django 3.2.12 on 2022-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewilgs', '0003_auto_20220206_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downlink',
            old_name='frame_time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='uplink',
            old_name='frame_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='downlink',
            name='receive_time',
        ),
        migrations.RemoveField(
            model_name='downlink',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='downlink',
            name='version',
        ),
        migrations.RemoveField(
            model_name='uplink',
            name='send_time',
        ),
        migrations.AddField(
            model_name='downlink',
            name='application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downlink',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplink',
            name='application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplink',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downlink',
            name='qos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='qos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
