# Generated by Django 3.2.12 on 2022-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewilgs', '0004_auto_20220420_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downlink',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uplink',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
