# Generated by Django 3.2.8 on 2021-12-16 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ewilgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delfic3_L0_telemetry',
            fields=[
                ('id', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ewilgs.downlink')),
                ('frame_time', models.DateTimeField(default=datetime.datetime.now)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
                ('receive_time', models.DateTimeField(default=datetime.datetime.now)),
                ('version', models.TextField(null=True)),
                ('processed', models.BooleanField(default=False)),
                ('frequency', models.FloatField(default=None, null=True)),
                ('qos', models.FloatField(default=None, null=True)),
                ('frame', models.TextField(default=None, null=True)),
                ('frame_binary', models.BinaryField(default=None, null=True)),
            ],
        ),
    ]
