# Generated by Django 3.2.12 on 2022-04-21 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=70, unique=True)),
                ('norad_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.TextField(blank=True, null=True)),
                ('frequency', models.FloatField()),
                ('qos', models.FloatField(blank=True, null=True)),
                ('frame', models.TextField(default=None, null=True)),
                ('frame_binary', models.BinaryField(default=None, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('radio_amateur', models.ForeignKey(db_column='radio_amateur', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('sat', models.ForeignKey(db_column='sat', on_delete=django.db.models.deletion.DO_NOTHING, to='transmission.satellite', to_field='sat')),
            ],
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(null=True)),
                ('tle', models.TextField()),
                ('sat', models.ForeignKey(db_column='sat', on_delete=django.db.models.deletion.DO_NOTHING, to='transmission.satellite', to_field='sat')),
            ],
        ),
        migrations.CreateModel(
            name='Downlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('qos', models.FloatField(blank=True, null=True)),
                ('frame', models.TextField(default=None, null=True)),
                ('frame_binary', models.BinaryField(default=None, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('radio_amateur', models.ForeignKey(db_column='radio_amateur', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('sat', models.ForeignKey(db_column='sat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transmission.satellite', to_field='sat')),
            ],
        ),
    ]
