# Generated by Django 3.2.15 on 2022-09-04 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('observer', models.CharField(max_length=32)),
                ('application', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('frame', models.TextField(default=None)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=32, unique=True)),
                ('norad_id', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.CharField(max_length=32)),
                ('application', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('invalid', models.BooleanField(blank=True, null=True)),
                ('frequency', models.FloatField()),
                ('frame', models.TextField(default=None)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(null=True)),
                ('tle', models.TextField()),
                ('sat', models.ForeignKey(db_column='sat', on_delete=django.db.models.deletion.DO_NOTHING, to='transmission.satellite', to_field='sat')),
            ],
        ),
    ]
