{
 "title": "DelfiPQ",
 "time": { "from": "2022-01-13T00:00:00.000Z", "to": "2024-01-08T23:59:59.999Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Solar Panels Currents + Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpCurrent\" or r[\"_field\"] == \"PanelYmCurrent\" or r[\"_field\"] == \"PanelXpCurrent\" or r[\"_field\"] == \"PanelXmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Currents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpCurrent\" or r[\"_field\"] == \"PanelYmCurrent\" or r[\"_field\"] == \"PanelXpCurrent\" or r[\"_field\"] == \"PanelXmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Voltages + Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpVoltage\" or r[\"_field\"] == \"PanelYmVoltage\" or r[\"_field\"] == \"PanelXpVoltage\" or r[\"_field\"] == \"PanelXmVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Voltages ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpVoltage\" or r[\"_field\"] == \"PanelYmVoltage\" or r[\"_field\"] == \"PanelXpVoltage\" or r[\"_field\"] == \"PanelXmVoltage\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> group(columns:[\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Temp + Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpTemperature\" or r[\"_field\"] == \"PanelXmTemperature\" or r[\"_field\"] == \"PanelXpTemperature\" or r[\"_field\"] == \"PanelYmTemperature\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Panels Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpTemperature\" or r[\"_field\"] == \"PanelXmTemperature\" or r[\"_field\"] == \"PanelXpTemperature\" or r[\"_field\"] == \"PanelYmTemperature\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PanelYp + Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpTemperature\" or r[\"_field\"] == \"PanelYpVoltage\" or r[\"_field\"] == \"PanelYpCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PanelYp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYpTemperature\" or r[\"_field\"] == \"PanelYpVoltage\" or r[\"_field\"] == \"PanelYpCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\" or r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Too High\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PanelYmCurrent + status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Valid\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PanelYmCurrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_downlink\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"DelfiPqRadioEPSTelemetry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PanelYmCurrent\")\n  |> filter(fn: (r) => r[\"status\"] == \"Too Low\" or r[\"status\"] == \"Valid\")\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}