{
 "title": "Latest Reception Times",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Receptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Delfi-PQ Last Reception",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_pq_raw_data\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r._measurement == \"delfi_pq_downlink_raw_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timestamp\") \n  |> last()\n"
    }
   ]
  },
  {
   "title": "Delfi-C3 Last Reception",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3_raw_data\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r._measurement == \"delfi_c3_downlink_raw_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timestamp\") \n  |> last()\n"
    }
   ]
  },
  {
   "title": "Delfi-Next Last Reception",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_next_raw_data\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r._measurement == \"delfi_next_downlink_raw_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timestamp\") \n  |> last()\n"
    }
   ]
  },
  {
   "title": "Da-Vinci-Satellite Last Reception",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"da_vinci_raw_data\")\n  |> range(start: 0, stop: now())\n  |> filter(fn: (r) => r._measurement == \"da_vinci_downlink_raw_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timestamp\") \n  |> last()\n"
    }
   ]
  }
 ]
}