{
 "title": "Overview",
 "time": { "from": "2008-04-28T00:00:00.000Z", "to": "2023-11-14T23:59:59.999Z" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> distinct(column: \"user\")\n  |> group()\n  |> unique(column: \"user\")\n  |> keep(columns: [\"user\"])"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n\n|> distinct(column: \"application\")\n//|> keep(columns: [\"_value\"])\n|> group()\n|> unique(column: \"application\")\n|> keep(columns: [\"application\"])"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"/static/delfi-c3.webp\" >"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Source",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "  from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processed\")\n  |> group(columns: [\"application\"], mode:\"by\")\n  |> count()\n  "
    }
   ]
  },
  {
   "title": "Frame Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processed\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  \n  |> filter(fn: (r) => \"${username}\" == \"All\" or r[\"user\"] == \"${username}\")   \n  |> filter(fn: (r) =>  \"${application}\" == \"All\" or r[\"application\"] == \"${application}\") \n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: count, column: \"processed\")\n  |> cumulativeSum(columns: [\"processed\"]) "
    }
   ]
  },
  {
   "title": "Last frame received by",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processed\")\n  |> group()\n  |> last()"
    }
   ]
  },
  {
   "title": "Last frame received on",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processed\")\n  |> group()\n  |> last()"
    }
   ]
  },
  {
   "title": "Last frame received using",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"_raw\")\n  |> filter(fn: (r) => r[\"_field\"] == \"processed\")\n  |> group()\n  |> last()"
    }
   ]
  }
 ]
}