{
 "title": "Payload",
 "time": { "from": "2008-04-28T00:00:00.000Z", "to": "2023-11-14T23:59:59.000Z" },
 "panels": [
  { "title": "Reference Diodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RD.V_ZpXp\" or r[\"_field\"] == \"RD.V_ZpXm\" or r[\"_field\"] == \"RD.V_ZmYp\" or r[\"_field\"] == \"RD.V_ZmYm\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RD.I_ZpXp\" or r[\"_field\"] == \"RD.I_ZpXm\" or r[\"_field\"] == \"RD.I_ZmYp\" or r[\"_field\"] == \"RD.I_ZmYm\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Thin-Film Solar Cells", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Thin-Film Solar Cells Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TFSC_T_ZmYm\" or r[\"_field\"] == \"TFSC_T_ZmYp\" or r[\"_field\"] == \"TFSC_T_ZpXm\" or r[\"_field\"] == \"TFSC_T_ZpXp\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns:[\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ZmYm Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TFSC_IV_ZmYm.V0\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V1\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V2\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V3\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V4\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V5\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V6\" or r[\"_field\"] == \"TFSC_IV_ZmYm.V7\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ZmYm Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"TFSC_IV_ZmYm.I0\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I1\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I2\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I3\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I4\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I5\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I6\" or r[\"_field\"] == \"TFSC_IV_ZmYm.I7\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Autonomous Wireless Sun Sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Supply Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AWSS.sensor_supply_voltage_Zm\" or r[\"_field\"] == \"AWSS.sensor_supply_voltage_Zp\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Payload\")\n  |> filter(fn: (r) => r[\"_field\"] == \"AWSS.sensor_temperature_Zm\" or r[\"_field\"] == \"AWSS.sensor_temperature_Zp\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}