{
 "title": "Telemetry",
 "time": { "from": "2008-04-28T00:00:00.000Z", "to": "2023-11-14T23:59:59.999Z" },
 "panels": [
  {
   "title": "Currents",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RAP1_Rx_I\" or r[\"_field\"] == \"RAP1_Tx_I\" or r[\"_field\"] == \"RAP2_Rx_I\" or r[\"_field\"] == \"RAP2_Tx_I\" or r[\"_field\"] == \"ComBo_I\" or r[\"_field\"] == \"FM430_I\" or r[\"_field\"] == \"MeBo_Zm_I\" or r[\"_field\"] == \"MeBo_Zp_I\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bus_V_dep\" or r[\"_field\"] == \"bus_V_sys\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\") \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"OBC_T\" or r[\"_field\"] == \"RAP1_T\" or r[\"_field\"] == \"RAP2_T\")\n  |> filter(fn: (r) => r[\"status\"] == \"Valid\")\n  |> group(columns: [\"_field\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Boot Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BootCounter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Boot Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BootNumber\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Frame Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"delfi_c3\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Housekeeping\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FrameNumber\")\n  |> group(columns: [\"_field\"], mode:\"by\")  \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}