# Generated by Django 3.2.8 on 2021-12-03 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delfin3xt_L0_telemetry',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('frame_time', models.TimeField(default=datetime.time)),
                ('send_time', models.TimeField(default=datetime.time)),
                ('receive_time', models.TimeField(default=datetime.time)),
                ('radio_amateur', models.IntegerField(default=None, null=True)),
                ('frame', models.BinaryField(default=None, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('frequency', models.FloatField(default=None, null=True)),
                ('qos', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
