remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs

title: DelfiTLM
github_repo_url: "https://github.com/iiacoban42/DelfiTLM/"
description: Ground Segment Software for CubeSats

aux_links:
  "Delfi Space on Twitter":
    - "//twitter.com/DelfiSpace"

  "DelfiTLM on GitHub":
    - "//github.com/iiacoban42/DelfiTLM/"

