# Generated by Django 3.2.8 on 2021-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20211111_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
